### ISSUE TITLE
migrate to voxpupuli

### ISSUE THREAD

**Issue by igalic** [voxpupuli/puppet-cassandra#394]
as per slack request, i'd like to get the ball rolling on migrating this module to voxpupuli.

**Comment by bastelfreak** [comment]
Hi @dallinb, I saw your message on slack. I send you an invitation to our github org, this allows you to migrate the repository. The workflow for a migration is explained at: https://voxpupuli.org/docs/

Let us know if you've any further questions. You can easily contact us here or via our IRC channel #voxpupuli on freenode.

**Comment by dallinb** [comment]
@igalic & @bastelfreak 

Thank you for organizing that.  I've accepted the invitation and will start working my way through the steps to migrate this module.

**Comment by dallinb** [comment]
I've transferred the repository from locp to the voxpupuli account and take a fork back to the locp account.  Will release from this new fork release 999.999.99 to locp/cassandra on Puppet Forge.

**Comment by igalic** [comment]
we don't have a redirect from https://github.com/locp/cassandra → https://github.com/voxpupuli/cassandra
maybe we should :)

**Comment by dallinb** [comment]
Looking at the names of all the modules in modulesync, should this git project be called `voxpupuli/puppet-cassandra` rather than just `voxpupuli/cassandra`?

**Comment by igalic** [comment]
@dallinb following conventions, yes, that would be good.

**Comment by dallinb** [comment]
@igalic I no longer seem to have access to the settings of `voxpupuli/cassandra` so please could somebody rename this project to `voxpupuli/puppet-cassandra` and I will submit PR's to complete items on this issues list (modulesync and plumbing for example).

**Comment by bastelfreak** [comment]
* adjusted the name
* checked github perms
* corrected forge link

**Comment by bastelfreak** [comment]
* did modulesync_config
* did modulesync
* generated plumbing

please checkout https://github.com/voxpupuli/puppet-cassandra/pull/404

**Comment by dallinb** [comment]
@bastelfreak thank you for sorting that out.  I'll sort out the conflicts over the weekend so that #404 can be merged.

**Comment by khaefeli** [comment]
could you also release it on puppet forge?

**Comment by dallinb** [comment]
@bastelfreak That's all the tests for #404 passing now.  Quite a chunk of changes (sorry).  Things that probably still need to be done are beaker test clarification and also the documentation.  Currently using yard.  Should this be changed and if so, does voxpupuli have any guidelines or preferences for how documentation should be delivered within a module?

**Comment by dallinb** [comment]
Hi @bastelfreak 
Thanks for your help so far. I'm pretty sure that's all items completed for the initial transfer of the module. I suspect there's some more work to do to make this module release ready for voxpupuli. Would it be possible to raise these items as separate issues? In the meantime (probably early next week I'm afraid) I'll submit pull requests for the more obvious things that need updating (e.g. removing the redundant CircleCI) configuration).

**Comment by bastelfreak** [comment]
Hi @dallinb, thanks for all the work. I will have a look through the module and rise separate issues.
