### ISSUE TITLE
Puppet catalogue generation is failing

### ISSUE THREAD

**Issue by chavavk** [voxpupuli/puppet-cassandra#427]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.7
- Ruby:
- Distribution:
- Module version: 2.7.0

## How to reproduce (e.g Puppet code you use)
Run puppet with older version
## What are you seeing
Boolean $manage_config_file           = true,

this line of code in init.pp
is causing failures when I tried to replace with previous version.
I do not see any benefit of  explicitly mentioning DataType Boolean here.
## What behaviour did you expect instead
It  should not cause compilation failure. Removing "Boolean" fixes the problem 
## Any additional information you'd like to impart
Removing "Boolean" fixes the problem and I am able to use it with Puppet 3.8.7 version

**Comment by juniorsysadmin** [comment]
Puppet 3 is EOL and is not supported for any Voxpupuli modules. See:
https://voxpupuli.org/blog/2016/12/22/putting-down-puppet-3/
