### ISSUE TITLE
ubuntu18

### ISSUE THREAD

**Issue by slamd64** [voxpupuli/puppet-cassandra#441]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.3
- Ruby:
- Distribution: Ubuntu 18.04
- Module version: 2.7.3
- Cassandra: not installled

## How to reproduce (e.g Puppet code you use)

Just include class in manifest and

puppet agent -t --verbose --debug | grep added

## What are you seeing

Debug: Facter: fact "backend_server_ip" resolved to null and will not be added.
Debug: Facter: fact "cassandrarelease" resolved to null and will not be added.
Debug: Facter: fact "cassandramajorversion" resolved to null and will not be added.
Debug: Facter: fact "cassandraminorversion" resolved to null and will not be added.
Debug: Facter: fact "cassandrapatchversion" resolved to null and will not be added.
Debug: Facter: fact "pe_version" resolved to null and will not be added.
Debug: Facter: fact "nginx_version" resolved to null and will not be added.
Debug: Facter: fact "pe_major_version" resolved to null and will not be added.
Debug: Facter: fact "pe_minor_version" resolved to null and will not be added.
Debug: Facter: fact "pe_patch_version" resolved to null and will not be added.
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Unknown variable: '::cassandrarelease'. at cassandra/manifests/schema/user.pp:28:6 at cassandra/manifests/schema.pp:111 on node cassandra

## What behaviour did you expect instead

I wonder it install Cassandra :) But Facter dont add variables and you trying to compare unpresent variable. For example in manifests/schema/user.pp:

  if $::cassandrarelease != undef {
    if versioncmp($::cassandrarelease, '2.2') < 0 {
      $operate_with_roles = false
    } else {
      $operate_with_roles = true
    }
  } else {
    $operate_with_roles = false
  }

**Comment by bastelfreak** [comment]
Hi @slamd64, we currently do not support Ubuntu 18.04:

https://github.com/voxpupuli/puppet-cassandra/blob/874bee1161825bdd8e3b6d4a3dd1787e8e9a1cfd/metadata.json#L73-L76

Are you able to provide a PR for it?
