### ISSUE TITLE
Wrong logic?

### ISSUE THREAD

**Issue by EcentriaGit** [voxpupuli/puppet-cassandra#459]
In examples/getting_started.pp#L150, there is an if-else block for calculating max_heap_size_in_mb. But it looks like the elsif branch makes not sense there -it is just overridden by the initial if. 

<pre>
if ($facts['memory']['system']['total_bytes'] / (1024*1024)) < 24576.0 {
  $max_heap_size_in_mb = floor(($facts['memory']['system']['total_bytes'] / (1024*1024)) / 2)
} elsif ($facts['memory']['system']['total_bytes'] / (1024*1024)) < 8192.0 {
  $max_heap_size_in_mb = floor(($facts['memory']['system']['total_bytes'] / (1024*1024)) / 4)
} else {
  $max_heap_size_in_mb = 8192
}
</pre>

Am I missing something about it?

**Comment by dallinb** [comment]
@EcentriaGit you're quite right, the logic is mistaken.  While the code in question has been edited, it was my original code that was incorrect.  Let me try and get myself back into the swing of Puppet again (for the first time in about four years) and I'll apply a PR.

**Comment by alexjfisher** [comment]
I'm surprised I didn't notice it when making the change for puppet-lint.

**Comment by dallinb** [comment]
Now I look at it a bit more, the refactor did change the unit size from megabytes to bytes but not the figures, so will fix that too while I'm at it ;-)
