### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by waipeng** [voxpupuli/puppet-cassandra#476]
Is it possible to have a new version? The latest, [v3.1.0](https://github.com/voxpupuli/puppet-cassandra/commits/v3.1.0), is almost 3 years old. 9f42eb5 a3171c2 will be very helpful for us needing to upgrade to newer stdlib.

Thanks for maintaining this module!

**Comment by kenyon** [comment]
#468 needs work.

**Comment by waipeng** [comment]
I see that there are thoughts of [archiving this repo]( https://github.com/voxpupuli/puppet-cassandra/pull/468#issuecomment-995691499 ).

I think it is ok, we will be moving off this in the mid term.
